export const SET_TICKETS_ARRAY = 'SET_TICKETS_ARRAY';
export const SET_NEW_TICKET_SUMMARY = 'SET_NEW_TICKET_SUMMARY';
export const SET_NEW_TICKET_DESCRIPTION = 'SET_NEW_TICKET_DESCRIPTION';
export const SET_NEW_TICKET_SEVERITY = 'SET_NEW_TICKET_SEVERITY';
export const SET_NEW_TICKET_STATUS = 'SET_NEW_TICKET_STATUS';
export const CLEAR_NEW_TICKET_DATA = 'CLEAR_NEW_TICKET_DATA';
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
export const SET_TICKET_ID_TO_EDIT = "SET_TICKET_ID_TO_EDIT";